/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./login.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        pacifico: ["Pacifico", "cursive"],
        poppins: ["Poppins"],
        roboto: ["Roboto"],
        satisfy: ["Satisfy"],
        skranji: ["Skranji"],
        nunito: ["Nunito"],
        barriecito: ["Barriecito"],
        caveat: ["Caveat"],
        concert: ["Concert One"],
        cookie: ["Cookie"],
        dancing: ["Dancing Script"],
        fugaz: ["Fugaz One"],
        itim: ["Itim"],
        josefin: ["Josefin Sans"],
        lato: ["Lato"],
        lilita: ["Lilita One"],
        luckiest: ["Luckiest Guy"],
        major: ["Major Mono Display"],
        marck: ["Marck Script"],
        montserrat: ["Montserrat"],
        mukta: ["Mukta"],
        open: ["Open Sans"],
        oswald: ["Oswald"],
        condensed: ["Roboto Condensed"],
        rubik: ["Rubik"],
        sacramento: ["Sacramento"],
        shadows: ["Shadows Into Light"],
        work: ["Work Sans"],
        yellowtail: ["Yellowtail"],
      },
    },
  },
  plugins: [],
}

